Repository DataJunction/dj, pull requests merged in 2022-10, with the labels that each got.

#220 chore: improve dependencies
  CONTRIBUTING.rst
  requirements/base.txt
  requirements/docker.txt
  requirements/test.in
  requirements/test.txt
  setup.cfg
Labels: chore, please merge if green

#222 docs: DB migration docs
  CONTRIBUTING.rst
  alembic/versions/2022_10_13_0054-71b291295ae1_update_schema_types.py
Labels: documentation

#217 Add Cockroach DB docker compose and examples
  .docker-env/.env-cockroachdb
  .docker-env/.env-postgres
  Makefile
  docker-compose.cockroachdb.yml
  docker-compose.druid.yaml
  docker-compose.yml
  examples/README.rst
  examples/cockroachdb/configs/databases/cockroachdb.yaml
  examples/cockroachdb/configs/nodes/kaggle/avg_play_time.yaml
  examples/cockroachdb/configs/nodes/kaggle/dimension/games.yaml
  examples/cockroachdb/configs/nodes/kaggle/num_italian_games.yaml
  examples/cockroachdb/configs/nodes/kaggle/num_play_events.yaml
  examples/cockroachdb/configs/nodes/kaggle/num_purchase_events.yaml
  examples/cockroachdb/configs/nodes/kaggle/source/games.yaml
  examples/cockroachdb/configs/nodes/kaggle/source/playtime.yaml
  examples/docker/cockroachdb/cockroachdb_examples_init.sql
  examples/docker/cockroachdb/cockroachdb_metadata_init.sql
  examples/docker/cockroachdb/steam-games.csv
  examples/docker/cockroachdb/steam-hours-played.csv
  requirements/docker.in
  requirements/docker.txt
Labels: enhancement

#224 chore: fix migration for SQLite
  CONTRIBUTING.rst
  alembic/versions/2022_04_30_1939-5f31ff8814e7_initial_migration.py
  alembic/versions/2022_04_30_2022-7f8367fdfa30_add_extra_params_to_database.py
  alembic/versions/2022_10_13_0054-71b291295ae1_update_schema_types.py
Labels: please merge if green

#227 Delete removed metrics
  dj/cli/compile.py
  tests/cli/compile_test.py
Labels: bug
